### ISSUE TITLE
Floating point exception (core dumped)

### ISSUE THREAD

**Issue by parashorea** [azerothcore/mod-tic-tac-toe#1]
Floating point exception (core dumped)

**Comment by Helias** [comment]
I see that this happens only on [-dry-run](https://github.com/azerothcore/mod-tic-tac-toe/actions/runs/8490646528/job/23266129198), how did you reproduce this?

**Comment by parashorea** [comment]
> I see that this happens only on [-dry-run](https://github.com/azerothcore/mod-tic-tac-toe/actions/runs/8490646528/job/23266129198), how did you reproduce this?

Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-46-generic x86_64)
After the build is completed, executing the command ./worldserver results in the error "Floating point exception (core dumped)".

**Comment by Helias** [comment]
fixed by https://github.com/azerothcore/mod-tic-tac-toe/commit/b15f2c47c75c10bb2325ed2be498c5239d06de9b
